# Render Blueprint Configuration
services:
  # --- Frontend Static Site ---
  - type: web
    name: techno-prompt
    runtime: static
    buildCommand: bash ./render-build.sh
    staticPublishPath: ./dist
    previews:
      generation: automatic
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # --- Backend Orchestrator ---
  - type: web
    name: orchestrator
    runtime: node
    plan: free
    buildCommand: npm ci
    startCommand: npm run start:orchestrator
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: ORCH_ALLOW_NO_REDIS
        value: 1
