# Render Blueprint Configuration
services:
  # Frontend Static Site Service
  - type: static_site
    name: techno-prompt
    buildCommand: bash ./render-build.sh
    publishPath: ./dist
    pullRequestPreviewsEnabled: true
    # SPA rewrite rule to handle client-side routing
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend Web Service
  - type: web
    name: orchestrator
    env: node
    buildCommand: npm install && npm run build:orchestrator
    startCommand: npm run start:orchestrator
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: ORCH_ALLOW_NO_REDIS
        value: 1